name: muezikfy
description: A music player
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  just_audio: ^0.9.36
  provider: ^6.1.1
  marquee: ^2.2.3
  just_audio_background: ^0.0.1-beta.11
  flutter_font_icons: ^2.2.7
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  bot_toast: ^4.1.3
  firebase_analytics: ^10.7.4
  on_audio_query: ^2.9.0
  sqflite: ^2.3.0
  intl: any
  path: ^1.8.3
  permission_handler: ^11.0.1
  cloud_firestore: ^4.13.6
  firebase_ui_firestore: ^1.5.15
  go_router: ^13.0.0
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  zoom_tap_animation: ^1.1.0
  firebase_storage: ^11.5.6


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/